# Generated by Django 4.0.3 on 2022-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sell_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
