# Generated by Django 4.0.3 on 2022-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sell_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='category',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
