# Generated by Django 4.0.3 on 2022-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sell_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='category',
            field=models.CharField(choices=[('Electronic Devices', 'GREEN'), ('Books', 'BLUE'), ('Cycles', 'RED'), ('Furniture', 'ORANGE')], default='Books', max_length=30),
        ),
    ]
