# Generated by Django 4.0.3 on 2022-03-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_sell_seller_alter_sell_description_and_more'),
        ('accounts', '0005_alter_sell_category'),
    ]

    operations = [
    ]
